export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const COURSE_FETCH_START = 'COURSE_FETCH_START';
export const COURSE_FETCH_FAILED = 'COURSE_FETCH_FAILED';
export const COURSE_FETCH_SUCCESS = 'COURSE_FETCH_SUCCESS';

export const STATION_FETCH_START = 'STATION_FETCH_START';
export const STATION_FETCH_FAILED = 'STATION_FETCH_FAILED';
export const STATION_FETCH_SUCCESS = 'STATION_FETCH_SUCCESS';